__title__ = 'KozmoDB Google Fit handler'
__package_name__ = 'kozmodb_google_fit_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for the Google Fit APIs"
__author__ = 'DigitransLab'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - kozmodb'
