__title__ = 'KozmoDB Microsoft SQL Server handler'
__package_name__ = 'kozmodb_mssql_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Microsoft SQL Server"
__author__ = 'KozmoDB Inc'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
