__title__ = "KozmoDB Discord handler"
__package_name__ = "kozmodb_discord_handler"
__version__ = "0.0.1"
__description__ = "KozmoDB handler for Discord"
__author__ = 'Jason Wiemels'
__github__ = "https://github.com/digitranslab/kozmodb"
__pypi__ = "https://pypi.org/project/kozmodb/"
__license__ = "MIT"
__copyright__ = "Copyright 2023 - kozmodb"
