__title__ = 'KozmoDB Altibase handler'
__package_name__ = 'kozmodb_altibase_handler'
__version__ = '0.0.2'
__description__ = "KozmoDB handler for Altibase"
__author__ = 'KozmoDB Inc'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
