__title__ = 'KozmoDB Newa APi handler'
__package_name__ = 'kozmodb_news_api_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for News API"
__author__ = 'Thimotee Kenmogne'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
