__title__ = 'KozmoDB TPOT handler'
__package_name__ = 'kozmodb_tpot_handler'
__version__ = '0.0.2'
__description__ = "KozmoDB handler for TPOT "
__author__ = 'Parthiv Makwana'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
