image:
  file: .gitpod.Dockerfile

ports:
  # Kozmodb GUI
  - port: 47334
    onOpen: open-preview

  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - name: kozmodb
    init: |
      pip install -U pip
      pip install -r requirements.txt
    command: |
      python -m kozmodb
