__title__ = 'KozmoDB Zotero handler'
__package_name__ = 'kozmodb_zotero_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Zotero"
__author__ = 'Elina Kapetanaki'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - kozmodb'
