__title__ = 'KozmoDB Vertica handler'
__package_name__ = 'kozmodb_vertica_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Vertica"
__author__ = 'Parthiv Makwana'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
