__title__ = 'kozmodb_sql'
__package_name__ = 'kozmodb_sql'
__version__ = '0.21.0'
__description__ = "Pure python SQL parser"
__email__ = "jorge@kozmodb.com"
__author__ = 'KozmoDB Inc'
__github__ = 'https://github.com/digitranslab/kozmodb_sql'
__pypi__ = 'https://pypi.org/project/kozmodb_sql'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2021- kozmodb'
