__title__ = 'KozmoDB Leonardo AI Handler'
__package_name__ = 'kozmodb_leonardo_ai_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB Handler for Leonardo AI"
__author__ = 'Tarun Chawla'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - kozmodb'
