__title__ = 'KozmoDB Amazon Bedrock handler'
__package_name__ = 'kozmodb_bedrock_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Amazon Bedrock"
__author__ = 'KozmoDB Inc.'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
