__title__ = 'KozmoDB Ray Serve handler'
__package_name__ = 'kozmodb_ray_serve_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Ray Serve"
__author__ = 'DigitransLab'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
