__title__ = 'KozmoDB MLflow handler'
__package_name__ = 'kozmodb_mlflow_handler'
__version__ = '0.0.2'
__description__ = "KozmoDB handler for MLflow"
__author__ = 'DigitransLab'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
