blank_issues_enabled: true
contact_links:
  - name: 1-on-1 Session
    url: https://cal.com/mobenchio/ec
    about: Speak directly with Taranjeet, the founder, to discuss issues, share feedback, or explore improvements for Kozmochain
  - name: Discord
    url: https://discord.gg/6PzXDgEjG5
    about: General community discussions
