__title__ = 'KozmoDB Azure Blob Storage handler'
__package_name__ = 'kozmodb_azure_blob_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Azure Blob Storage"
__author__ = 'Fabian Jevon'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- kozmodb'
