__title__ = "KozmoDB Microsoft One Drive handler"
__package_name__ = "kozmodb_ms_one_drive_handler"
__version__ = "0.0.1"
__description__ = "KozmoDB handler for Microsoft One Drive"
__author__ = 'DigitransLab'
__github__ = "https://github.com/digitranslab/kozmodb"
__pypi__ = "https://pypi.org/project/kozmodb/"
__license__ = "MIT"
__copyright__ = "Copyright 2024 - kozmodb"
