__title__ = 'KozmoDB Apache Doris handler'
__package_name__ = 'kozmodb_apache_doris_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Apache Doris"
__author__ = 'Aditya Azad'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
