__title__ = "KozmoDB Microsoft Teams handler"
__package_name__ = "kozmodb_ms_teams_handler"
__version__ = "0.0.1"
__description__ = "KozmoDB handler for Microsoft Teams"
__author__ = 'DigitransLab'
__github__ = "https://github.com/digitranslab/kozmodb"
__pypi__ = "https://pypi.org/project/kozmodb/"
__license__ = "MIT"
__copyright__ = "Copyright 2023 - kozmodb"
