__title__ = 'KozmoDB Financial Modeling Prep handler'
__package_name__ = 'kozmodb_financial_modeling_prep_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Financial Modeling Prep API"
__author__ = 'Riyana Dutta'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- kozmodb'
