__title__ = 'KozmoDB Amazon Athena handler'
__package_name__ = 'kozmodb_athena_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Amazon Athena"
__author__ = 'Ryan Watts'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
