__title__ = 'KozmoDB Hive handler'
__package_name__ = 'kozmodb_hive_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Hive2"
__author__ = 'Biswadip Paul'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
