version: "3.9"

services:
  backend:
    container_name: kozmochain_discord_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - variables.env