__title__ = 'KozmoDB Gmail handler'
__package_name__ = 'kozmodb_gmail_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Gmail"
__author__ = 'Rajeev R Sharma and Marios Ajdini'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
