name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_review:

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
    
jobs:
  CLAssistant:
    runs-on: mdb-dev
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: cla-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'assets/contributions-agreement/signatures/cla.json'
          path-to-document: 'https://github.com/digitranslab/kozmodb_native/blob/stable/assets/contributions-agreement/individual-contributor.md'
          branch: 'staging'
          allowlist: bot*, ZoranPandovski, torrmal, Stpmax, paxcema, kozmodbadmin, Ricram2, ea-rus, ilia-tsyplenkov, tomhuds
