__title__ = 'KozmoDB HackerNews handler'
__package_name__ = 'kozmodb_hn_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for HackerNews"
__author__ = 'Maro Akpobi'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- kozmodb'
