__title__ = 'KozmoDB Teradata handler'
__package_name__ = 'kozmodb_teradata_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Teradata"
__author__ = 'Sudipto Ghosh'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 - kozmodb'
