__title__ = 'KozmoDB Google Content API for Shopping handler'
__package_name__ = 'kozmodb_google_content_shopping_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for the Google Content API for Shopping"
__author__ = 'Panagiotis-Alexios Spanakis'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 - kozmodb'
