__title__ = 'KozmoDB PirateWeather API handler'
__package_name__ = 'kozmodb_pirateweather_api_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for the PriateWeather API"
__author__ = 'Patrick Sean Klein'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
