version: "3.9"

services:
  backend:
    container_name: kozmochain-backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    image: kozmochain/backend
    ports:
      - "8000:8000"

  frontend:
    container_name: kozmochain-frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kozmochain/frontend
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
