__title__ = 'KozmoDB SAP SQL Anywhere handler'
__package_name__ = 'kozmodb_sqlany_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for SAP SQL Anywhere"
__author__ = 'Michael Lantz'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 - kozmodb'
