__title__ = 'KozmoDB Unify handler'
__package_name__ = 'kozmodb_unify_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Unify"
__author__ = 'Janice Herman & Mohamed Abderrahim'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - kozmodb'
