__title__ = 'KozmoDB Ingres handler'
__package_name__ = 'kozmodb_ingres_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for Ingres"
__author__ = 'Panagiotis-Alexios Spanakis and Theodoros Malikourtis'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- kozmodb'
