__title__ = 'Kozmo Endpoint handler'
__package_name__ = 'kozmo_endpoint_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for the Kozmo Endpoint"
__author__ = 'DigitransLab'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 - kozmodb'
