services:
  kozmodb_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - kozmodb_storage:/kozmodb/storage
  kozmemory-mcp:
    image: kozmodb/kozmemory-mcp
    build: api/
    environment:
      - USER
      - API_KEY
    env_file:
      - api/.env
    depends_on:
      - kozmodb_store
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/kozmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
  kozmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: kozmodb/kozmemory-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}

volumes:
  kozmodb_storage:
