name: KozmoDB Evaluator Tests Workflow

on:
  push:
    paths:
      - 'packages/kozmodb_evaluator/**'
  pull_request:
    branches:
      - stable
      - staging
    paths:
      - 'packages/kozmodb_evaluator/**'
    paths-ignore:
      - 'packages/kozmodb_evaluator/docssrc/**'
      - 'packages/kozmodb_evaluator/**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10","3.11", "3.12", "3.13"]
    defaults:
      run:
        working-directory: ./packages/kozmodb_evaluator
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -e .
        pip install flake8
        pip install coverage
    - name: Lint with flake8
      run: |
        python -m flake8 .
    - name: Test with unittest
      run: |
        # Run all the "standard" tests
        coverage run -m unittest discover tests
    - name: Test coverage report
      run: |
        coverage report --omit=tests/*

  deploy:
    runs-on: ubuntu-latest
    environment: PublishCI
    needs: test
    if: github.ref == 'refs/heads/stable'
    defaults:
      run:
        working-directory: ./packages/kozmodb_evaluator
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build
      run: poetry build
    - name: Publish
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry publish --dry-run
        poetry publish
