__title__ = 'KozmoDB Web crawl handler'
__package_name__ = 'kozmodb_web_handler'
__version__ = '0.0.1'
__description__ = "KozmoDB handler for crawling web-sites"
__author__ = 'KozmoDB Inc'
__github__ = 'https://github.com/digitranslab/kozmodb'
__pypi__ = 'https://pypi.org/project/kozmodb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 - KozmoDB'
